spring:
  servlet:
    multipart:
      max-file-size: 10MB # 요청한 파일 한 개의 크기
      max-request-size: 10MB # 요청한 파일 전체의 크기

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            redirect-uri: ${oauth.redirect.uri}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client_name: kakao
          naver:
            client-id: ${naver.client.id}
            client-secret: ${naver.client.secret}
            redirect-uri: ${oauth.redirect.uri}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname
              - profile_image
            client-name: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jwt:
  token:
    secret-key: ${jwt.secret}
  access:
    expiration: 3600000  # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prod