spring:
  servlet:
    multipart:
      max-file-size: 10MB # 요청한 파일 한 개의 크기
      max-request-size: 10MB # 요청한 파일 전체의 크기

  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

jwt:
  token:
    secret-key: ${jwt.secret}
  access:
    expiration: 3600000  # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
    credentials:
      access-key: ${s3.access.key}
      secret-key: ${s3.secret.key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    persistAuthorization: true
    url: /docs/index.yaml
    path: /swagger

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

slack:
  webhook:
    url: ${slack.webhook.url}

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prod