spring:
  servlet:
    multipart:
      max-file-size: 10MB # 요청한 파일 한 개의 크기
      max-request-size: 10MB # 요청한 파일 전체의 크기

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prod